### ISSUE TITLE
JPEGMini Pro error

### ISSUE THREAD

**Issue by GaryJones** [JamieMason/ImageOptim-CLI#103]
`/usr/local/bin/imageOptimAppleScriptLib:3271:3311: execution error: System Events got an error: Can’t get button "Go" of sheet 1 of window 1 of process "JPEGmini Pro". (-1728)`

**Comment by JamieMason** [comment]
Thanks @GaryJones I'll get onto this soon — which version of OSX are you running please?

**Comment by GaryJones** [comment]
10.9.5

**Comment by mattparrilla** [comment]
+1, also 10.9.5.

imageoptim-cli 1.11.4
jpegmini 1.8.7
imageoptim 1.5.4

Really cool tool. Excited to bring it into my workflow!

**Comment by mexyn** [comment]
Same problem here...

**Comment by falzhobel** [comment]
Also getting the error on Yosemite 10.10.2, with JPEGmini 1.8.7

But I can confirm it works with fine JPEGmini 1.8.2, so it's definitely a problem with the newest version.

**Comment by JamieMason** [comment]
I think the local fix in ff8fc16 for issue #98 should also address this.

**Comment by falzhobel** [comment]
Are you going to add this commit to a new release?

Thanks for the quick reply.

**Comment by JamieMason** [comment]
Merging into develop now then pushing there, but I have to head out soon so the release will be a little later

**Comment by JamieMason** [comment]
I'm not ready to do a release just yet, but anyone wanting to try the latest version can run;

    npm uninstall -g imageoptim-cli
    npm install -g git+https://github.com:JamieMason/ImageOptim-CLI.git#ad692863385e69a9231c8aaea1c0f3dcf736247a

**Comment by falzhobel** [comment]
Works fine for me with the latest version, thanks :+1:

**Comment by GaryJones** [comment]
> anyone wanting to try the latest version can run

Works a treat!

May well be a different Issue, but the JPEGMini Pro paused at the confirmation that images in the folder I tested were going to be overwritten. Instead of me always accepting that, could a option flag be passed to imageoptim-cli so that it would go ahead and click continue for me?

**Comment by JamieMason** [comment]
Hey @GaryJones, that _should_ only happen the first time you run JPEGMini Pro, am I right? Or does it happen on every run? We could raise an issue for an enhancement I guess, it's a tricky bit of work though and would be fairly low priority if it does just happen on first run.

**Comment by GaryJones** [comment]
It happens every time if you don't select the Don't Show Again on the confirmation, or if you turn "Warn me before replacing photos" option back on in Preferences.

![screenshot 2015-02-16 12 15 34](https://cloud.githubusercontent.com/assets/88371/6211768/8de3c5ac-b5d5-11e4-8ffd-062721e5fdd2.png)


![screenshot 2015-02-16 12 14 24](https://cloud.githubusercontent.com/assets/88371/6211764/7553b402-b5d5-11e4-81e9-53b2c267e314.png)

**Comment by reintroducing** [comment]
I'm running into the same issue as the original posted here and its great to see a fix is already in place.  Subscribing to be informed of the new release. Thanks for the fantastic work on this!

**Comment by JamieMason** [comment]
Released 1.11.6
