### ISSUE TITLE
--quit closes JPEGmini but not ImageOptim

### ISSUE THREAD

**Issue by jrean** [JamieMason/ImageOptim-CLI#105]
Hi Jamie,
Thank you for you amazing work!

Little question, when using the -j flag it correctly pre-process photos with JPEGmini BUT it seems to not take care of the "Resize photo" option (when ticked). Did I miss something?

Do you recommend another cli tool to resize photos before applying ImageOptim?

Last but not least, when I use the flag -q it close JPEGmini after the process but still keep ImageOptim open! Normal? (OSX 10.10.1)

Regards.

**Comment by JamieMason** [comment]
Thanks @jrean you're very welcome. Are you running the latest version of this project? The following command `imageoptim --version` should say `1.11.4`.

**Comment by jrean** [comment]
Hi,

Yes it outputs 1.11.4
Running under iTerm2 and everything seems to be up to date. My main concern is to understand why it doesn't use the setting of resizing images while JpegMini pre-processing.

Closing ImageOptim Gui by myself is not really a pb :-)

Can I supply more "debug" details?

Regards.

**Comment by JamieMason** [comment]
I'll need to get back to you when I'm on my own machine — I have to admit, I haven't noticed the resize option in JPEGmini.

**Comment by jrean** [comment]
Take your time :-)
I used to use the "sips" cmd from terminal but I noticed JPEGmini offers  part of such functionality so I decided to give it a try ...

Keep me posted.

:-)

**Comment by jrean** [comment]
Hi,

Did you check?

Regards.

**Comment by JamieMason** [comment]
No, I've still not been on my own machine. I work full time and also travel a lot.

**Comment by JamieMason** [comment]
Hey @jrean, I have a theory I want to check with you. 

I see the setting in preferences with a folder to set as well.

+ When that is set in preferences, does the results output say there were no savings?
+ If you go to the folder you set in that option, do you find images there which are lighter and resized?

**Comment by JamieMason** [comment]
I'm not ready to do a release just yet, but anyone wanting to try the latest version can run;

    npm uninstall -g imageoptim-cli
    npm install -g git+https://github.com:JamieMason/ImageOptim-CLI.git#ad692863385e69a9231c8aaea1c0f3dcf736247a
