### ISSUE TITLE
imageoptim-cli error using jpeg-mini lite

### ISSUE THREAD

**Issue by mdevane** [JamieMason/ImageOptim-CLI#106]
Have set up ImageOptim, ImageAlpha, jpegMini, and imageoptim-cli on my MacPro running Mavericks.  All installed properly and imageoptim-cli has tested OK from Terminal.  When I add jpegMini to the mix using the following command:

***imageoptim -j -d test/edgewater/dm***, 

I received the following msg:

***/usr/local/bin/imageOptimAppleScriptLib:2886:2962: execution error: System Events got an error: Can’t get sheet 1 of window 1 of process "JPEGmini Lite". Invalid index. (-1719)***

imageoptim-cli then skips the jpegMini compression step and goes on to compress losslessly using ImageOptim.

I then figured out that JPEGmini lite UI needs to have an initial button clicked so that the **Drop Photos Here** dialog is showing.  When I reran the command (after setting screen properly), I received a different error:

***/usr/local/bin/imageOptimAppleScriptLib:3271:3311: execution error: System Events got an error: Can’t get button "Go" of sheet 1 of window 1 of process "JPEGmini Lite". (-1728)***

Progress!!  But when I attempted to manually click the Go button on JPEGmini lite, I received a new error:

***The folder can't be found.***

So, regardless of whether we can fix the UI control issues, there appears to be another issue with the file location, since JPEGmini lite will not even work in manual mode using the temp location passed thru by imageOptim-cli.

Any suggestions on how to resolve? am planning to create a simple one-line shell script, which can be added to a Hazel watch-folder.  I process several hundred images per day thru Lightroom and would like to automate the optimization step of the exported images. will purchase full version of JPEGMini assuming I can get imageOptim-cli working as needed.

Thanks for a great product otherwise,

Mark

**Comment by JamieMason** [comment]
I think the local fix in ff8fc16 for issue #98 should also address this.

**Comment by JamieMason** [comment]
I'm not ready to do a release just yet, but anyone wanting to try the latest version can run;

    npm uninstall -g imageoptim-cli
    npm install -g git+https://github.com:JamieMason/ImageOptim-CLI.git#ad692863385e69a9231c8aaea1c0f3dcf736247a

**Comment by mdevane** [comment]
Hi Jamie - 

1. Is this install below going to add the pre-release version mentioned in your previous email?

2. You mention in your article that ImageOptim-cli can be used in Automator scripts.  I have been trying to get this working this morning to no avail.  Any suggestions/examples you can point me to?  I have been trying to create a simple shell script, but I keep getting error:

	-: line1: imageoptim: command not found (127)

but when I run it from Terminal I have no issues — is there a trick??  Not sure how to pass the folder parameter into the Shell script so that ImageOptim-cli can run on the contents.

Mark

**Comment by JamieMason** [comment]
Hey @mdevane,

1) That install is the pre-release version yes, it includes fixes for #106, #105, #103, #98.

2) Automator

1. First go to your Terminal and run `which imageoptim` to find out where the bin is installed (in my case `/usr/local/bin/imageoptim`).
1. In Automator, you need a *Run Shell Script* action with;
    1. The `/bin/bash` shell.
    1. Pass input as arguments.
    1. The contents of the script as;

        ```bash
        find "$@" | /usr/local/bin/imageoptim # (--quit etc here if needed)`
        ```

The input passed as arguments would come from the "Ask for Finder Items" action, or similar depending on what you're building.

Thanks,

Jamie

**Comment by mdevane** [comment]
Hi Jamie - 

1) will dl new pre-release and test later today.
2) worked perfectly - thx very much!

Mark

**Comment by JamieMason** [comment]
Thanks @mdevane that would be really useful to have you run a test for me.

**Comment by mdevane** [comment]
OK - some results on new pre-release:

1) when run from working directory on home volume, new version worked, although on the 1st run, the macro stopped midway waiting for user input that had not been coded:  confirmation that it was OK to overwrite existing files.  Once that button was manually clicked, the macro completed OK.  On subsequent runs, the macro ran to completion, because JPEGmini Lite was no longer looking for that particular user input.  You may want to add that step into the Applescript.

2) I originally had been using a test folder of pics located on a Thunderbolt scratch drive array.  When I changed my working directory in Terminal to the Scratch/test directory and then attempted to run cli, I ran into the same problems as before and JPEGmini Lite would terminate unsuccessfully as it could not locate the folder (see attached Dropbox screenshot: https://dl.dropboxusercontent.com/u/315023/2015-02-12%2010.41.09%20am.pdf ). It sounds as if you are expecting the script to be run from the user home directory or something else is hardcoded in script, causing it to fail.  Not sure how to guide you further.

3) I next reran the script in Terminal out of my home directory but pointing to the directory on the RAID array.  This test also worked fine.

4) based on results above, it would appear that the script expects to run from from home volume, but files can be accessed on any volume.

—————————————

5) back to my Automator question, although the instruction you gave me work perfectly, I believe that they are using a direct call to ImageOptim.app.  What I am hoping to automate is calling ImageOptim-cli thru the bash script, not ImageOptim.app.  If so, what changes would need to be made to Bash script?

Thanks and hope this info helps, 

Mark

**Comment by JamieMason** [comment]
1) I should document this but yes, as you had done, currently you need to manually click off those dialogs when running JPEGmini for the first time.
2) I've never actually tried running this over a volume other than my mac hard drive, what does the command you're using look like? And also the `echo $PWD` when on that volume?
3) This is more typical behaviour, to be anywhere on your mac volume but referencing files elsewhere either by absolute or relative paths.
4) That's right.
5) That script is referring to imageoptim-cli, the command line script is called `imageoptim` — if you add the --jpeg-mini flag for example it should call that.

**Comment by mdevane** [comment]
see comments below:

On Feb 13, 2015, at 9:10 AM, Jamie Mason <notifications@github.com> wrote:

> 1) I should document this but yes, as you had done, currently you need to manually click off those dialogs when running JPEGmini for the first time.
> 2) I've never actually tried running this over a volume other than my mac hard drive, what does the command you're using look like? And also the echo $PWD when on that volume?  I used the normal command structure = imageoptim -j -d path-to-folder = imageoptim -j -d testpics
> 
following is the error received:

 /usr/local/bin/imageOptimAppleScriptLib:3026:3102: execution error: System Events got an error: Can’t get sheet 1 of window 1 of process "JPEGmini Lite". Invalid index. (-1719)

btw - in each of the cases where JPEGmini lite has failed, ImageOptim runs with no problems afterwards as next step in the Applescript.
> 3) This is more typical behaviour, to be anywhere on your mac volume but referencing files elsewhere either by absolute or relative paths.
> 4) That's right.
> 5) That script is referring to imageoptim-cli, the command line script is called imageoptim — if you add the --jpeg-mini flag for example it should call that. OK, I tried:
> 
find "$@" | /usr/local/bin/imageoptim #

which worked, but did not call any program other than imageOptim, and then I tried:

find "$@" | /usr/local/bin/imageoptim # -j

which failed, and then:

find "$@" | /usr/local/bin/imageoptim -j

which worked.  What does “#” do, and why does it not work in 2nd use case?

**Comment by JamieMason** [comment]
The # was a single line comment, just so I could mention where the options go that's all.

Are the using the pre-release version from [above](https://github.com/JamieMason/ImageOptim-CLI/issues/106#issuecomment-74135476)? If so, I will need to look into what could be wrong on Mavericks, I'm on Yosemite here at home.

**Comment by JamieMason** [comment]
Released 1.11.6

**Comment by mdevane** [comment]
pre-release - yes
OS - Mavericks

**Comment by JamieMason** [comment]
Which of the things we've discussed are still pending please? Thanks.
