### ISSUE TITLE
Optimize a single file from within a bash script

### ISSUE THREAD

**Issue by nwtn** [JamieMason/ImageOptim-CLI#110]
To optimize a single file, the documentation says to do something like:

````
find path -name 'filename' | imageoptim
````

This works totally fine when I do it directly in the console, but I'm hitting some errors when I try to do this from within a bash script. I have this in my script:

````
find default/300/ -name '$fn' | imageoptim -q
````

$fn is set correctly and the file exists, but my script produces:

````
sort: open failed: /var/folders/98/7n0x3r2d5pg73_mz6pzyk8vw0000gq/T//imageoptim-cli/index.txt: No such file or directory
Running ImageOptim...
Runtime error (func=(main), adr=9): Divide by zero
(standard_in) 2: parse error
TOTAL was: 0kb now: 0kb saving: 0kb (%) quality: %
````

Do you have any suggestions for how I can optimize a single file from within a bash script? Thanks.

**Comment by JamieMason** [comment]
Sorry for the slow reply @nwtn — has there been any change since the above?

**Comment by nwtn** [comment]
I'm not sure if there was an error with my previous script, or if the issue is resolved, but I'm not seeing this anymore.

Script:

```bash
fn=photo1.jpg
echo $fn
find ./ -name $fn | imageoptim -q
```

Results:

```bash
dnewton@newtron ~/Desktop/test 👍  ls -l
total 504
-rw-r--r--  1 dnewton  staff      57 29 May 13:22 imageoptim.sh
-rw-r--r--@ 1 dnewton  staff  132897 29 May 13:22 photo1.jpg
-rw-r--r--  1 dnewton  staff  118379 29 May 13:20 photo2.jpg
dnewton@newtron ~/Desktop/test 👍  . imageoptim.sh
photo1.jpg
Running ImageOptim...
.//photo1.jpg was: 132.897kb now: 118.379kb saving: 14.518kb (10.00%) quality: 100%
TOTAL was: 132.897kb now: 118.379kb saving: 14.518kb (10.00%) quality: 100%
dnewton@newtron ~/Desktop/test 👍  find ./ -name photo2.jpg | imageoptim -q
Running ImageOptim...
.//photo2.jpg was: 132.897kb now: 118.379kb saving: 14.518kb (10.00%) quality: 100%
TOTAL was: 132.897kb now: 118.379kb saving: 14.518kb (10.00%) quality: 100%
dnewton@newtron ~/Desktop/test 👍
```

Closing.

**Comment by nwtn** [comment]
Just looked at the original issue, and I think the issue was mine afterall: the `$fn` in the script shouldn't have had quotes around it. Sorry for the trouble.

**Comment by JamieMason** [comment]
No problem at all, thanks
