### ISSUE TITLE
osascript: command not found

### ISSUE THREAD

**Issue by kenetik** [JamieMason/ImageOptim-CLI#111]
[user@localhost Optimized]$ sudo imageOptim -d "/home/Optimized"
    /usr/bin/imageOptimBashLib: line 447: osascript: command not found
    /usr/bin/imageOptimBashLib: line 451: osascript: command not found
    /usr/bin/imageOptim: line 64: osascript: command not found
    /usr/bin/imageOptimBashLib: line 455: osascript: command not found
    find: unknown predicate `-E'
    sort: cannot read: /imageoptim-cli/index.txt: No such file or directory
    Running ImageOptim...
    /usr/bin/imageOptimBashLib: line 490: osascript: command not found
    /usr/bin/imageOptimBashLib: line 492: osascript: command not found
    Runtime error (func=(main), adr=9): Divide by zero
    (standard_in) 2: syntax error
    TOTAL was: 0kb now: 0kb saving: 0kb (%) quality: %

**Comment by dkubb** [comment]
This was probably caused by having GNU find in the `$PATH` ahead of the one that ships with OSX.

**Comment by nebulousdog** [comment]
I'm seeing the same thing. I installed via yarn, and am on Ubuntu Studio.

```bash
> $(yarn bin)/imageOptim --version
1.15.4

> lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

$(yarn bin)/imageOptim --directory path/to/images                                                                           
~/my/path/node_modules/.bin/imageOptimBashLib: line 461: osascript: command not found
~/my/path/node_modules/.bin/imageOptimBashLib: line 465: osascript: command not found
~/my/path/node_modules/.bin/imageOptim: line 74: osascript: command not found
~/my/path/node_modules/.bin/imageOptimBashLib: line 469: osascript: command not found
find: unknown predicate `-E'
```

**Comment by kornelski** [comment]
ImageOptim-CLI is a macOS app. It does not work on Ubuntu.
