### ISSUE TITLE
ImageOptim 1.6 changes

### ISSUE THREAD

**Issue by pornel** [JamieMason/ImageOptim-CLI#113]
Heads up: pngquant bundled with ImageOptim is going to move from `ImageOptim.app/Contents/MacOS/pngquant` to `ImageOptim.app/Contents/Frameworks/ImageOptimGPL.framework/Resources/pngquant`. I could add a symlink in the old location, but I see you're using your own version anyway.

The new embedded framework finally makes it possible to run optimizations without the main ImageOptim UI!

So far I've only used it for Apple Mail extension, but of course it could be used to improve CLI support. Let me know if you have any wishes for the interface.

**Comment by JamieMason** [comment]
Appreciate this info, thanks @pornel.
