### ISSUE TITLE
imageOptim doesn't quit

### ISSUE THREAD

**Issue by wearhere** [JamieMason/ImageOptim-CLI#114]
After installing ImageOptim and ImageAlpha (where do I need to put these btw? Is `/Applications` ok?) and ImageOptim-CLI, I run `imageOptim -q -a -d /directory/of/images` and see:

```
Running ImageAlpha...
Running ImageOptim...
```

and then ImageOptim-CLI just hangs without terminating nor further output. (But, FWIW, the activity indicator present next to the Terminal tab name after ImageOptim-CLI starts up

<img width="207" alt="screen shot 2015-07-16 at 7 10 11 pm" src="https://cloud.githubusercontent.com/assets/110000/8739309/d783ad64-2bee-11e5-870b-b67120655ec1.png">

has gone away.)

Any idea what's going on?

**Comment by JamieMason** [comment]
Hey @wearhere,
`/Applications` is the correct place. Can you confirm that the ImageOptim app isn't still running? It should be visible in your dock.

Thanks.

**Comment by wearhere** [comment]
Ah, it was indeed running! I didn't realize how long it would take to process my images—it would be nice if it were possible for you to provide some sort of progress information. Thanks for clarifying!
