### ISSUE TITLE
Error when trying to run ImageOptim, JPEG Mini, and Image Alpha from the pre-commit hook

### ISSUE THREAD

**Issue by SPJPGRD** [JamieMason/ImageOptim-CLI#116]
I was looking to take the pre-commit hook a bit farther and run it through all the optimizers, and I can't seem to figure it out.

Here's the version you provided (which works):
```
images=$(git diff --exit-code --cached --name-only --diff-filter=ACM -- '*.png' '*.jpg')
$(exit $?) || echo $images | imageoptim && git add $images
```

Here's one example of a modified version I made. I've tried a lot of combinations and all result in roughly the same type of failure.
```
images=$(git diff --exit-code --cached --name-only --diff-filter=ACM -- '*.png' '*.jpg')
$(exit $?) || echo $images | imageoptim -a -j && git add $images
```

This error is probably a result of my inexperience with this.

```
Ignored as neither file or directory:
Development/Demo/test-a-11.jpg
Development/Demo/test-b-11.png
sort: open failed: /var/folders/yf/fp9rgqlx39x0r8svf6c605tr0000gp/T//imageoptim-cli/index.txt: No such file or directory
Running ImageAlpha...
find: /var/folders/yf/fp9rgqlx39x0r8svf6c605tr0000gp/T//imageoptim-cli/png: No such file or directory
Running JPEGmini...
Running ImageOptim...
Runtime error (func=(main), adr=9): Divide by zero
(standard_in) 2: parse error
TOTAL was: 0kb now: 0kb saving: 0kb (%) quality: %
```

I am running the latest version (1.11.6) √

If this wasn't intended to be used like this, then it's all good!

**Comment by JamieMason** [comment]
Hi @SPJPGRD,
I'm sending this without having run it, so it may not help, but not quoting variable names containing paths is a common gotcha which will result in failures if any of the paths contain spaces;

```bash
images=$(git diff --exit-code --cached --name-only --diff-filter=ACM -- '*.png' '*.jpg')
$(exit $?) || echo "$images" | imageoptim -a -j && git add "$images"
```

It's a bit of a pot shot, but I hope this helps a little.

Thanks,

Jamie

**Comment by JamieMason** [comment]
Hi @SPJPGRD,
Thanks for raising this, the issue could be with my original script in that the `$images` variable is not quoted, which will cause issues if any of the file paths contain spaces.

Please could you try the following?

```bash
images=$(git diff --exit-code --cached --name-only --diff-filter=ACM -- '*.png' '*.jpg')
$(exit $?) || echo "$images" | imageoptim -a -j && git add "$images"
```

**Comment by SPJPGRD** [comment]
Hey @JamieMason •

That did the trick.
Thanks for the quick response!
