### ISSUE TITLE
Optimize recursive directories?

### ISSUE THREAD

**Issue by Horttcore** [JamieMason/ImageOptim-CLI#120]
Hi there,

great tool!

How does it optimize directories recursive?

Cheers Ralf

**Comment by JamieMason** [comment]
Thanks @Horttcore, 
Whenever a directory is passed into ImageOptim-CLI it optimises every image within it using [this `find` command](https://github.com/JamieMason/ImageOptim-CLI/blob/master/bin/imageOptimBashLib#L286-L292), so directories within directories get included that way.

Is that what you were asking about?

**Comment by Horttcore** [comment]
Not exactly, here is an example if I try to optimize a WordPress upload folder.

Folder structure is 

…
uploads/2015/11
uploads/2015/12
uploads/2016/01
…

`➜  wp-content git:(master) imageoptim --directory uploads
sort: string comparison failed: Illegal byte sequence
sort: Set LC_ALL='C' to work around the problem.
sort: The strings compared were `UPLOADS/2015/04/MOTIV\302\200\223MINIQEE-480X195.JPG' and `UPLOADS/2015/04/MOTIV\302\200\223MINIQEE.JPG'.
Running ImageOptim...
Runtime error (func=(main), adr=9): Divide by zero
(standard_in) 2: parse error
TOTAL was: 0kb now: 0kb saving: 0kb (%) quality: %`

No image is optimized, if I try `imageoptim --directory uploads/2016/01` it works as expected.

Maybe its my enviroment?

**Comment by JamieMason** [comment]
Could you tell me some more about the block starting with `➜` please?

**Comment by Horttcore** [comment]
Ah thats just because I use ohmyzsh

**Comment by JamieMason** [comment]
I've not used ohmyzsh before, I couldn't say whether ImageOptim-CLI supports that.

The directory structure `UPLOADS/2015/04/MOTIV\302\200\223MINIQEE.JPG` which mixes `/`s and `\` isn't something I've ever seen before, is that valid? That could be the cause.
