### ISSUE TITLE
404: Enable access for assistive devices in OS X Yosemite.

### ISSUE THREAD

**Issue by JamieMason** [JamieMason/ImageOptim-CLI#121]
"Enable access for assistive devices in OS X Yosemite." link in README is a 404.

**Comment by JamieMason** [comment]
Add El Capitan link as well: https://support.apple.com/kb/PH21504?locale=en_US&viewlocale=en_US

**Comment by jeffmcneill** [comment]
Yes, the Yosemite link is still a 404, but the instructions in the link to Mavericks still works and has screen shots. The El Capitan link is text-only, but again, the procedure hasn't changed. Suggest removing the Yosemite link to klabouche.com and also simply remove the word "Mavericks" from the link text to the Apple support page. That will work for everyone.
