### ISSUE TITLE
How to run image-alpha to reduce to 32 colors?

### ISSUE THREAD

**Issue by sogen** [JamieMason/ImageOptim-CLI#123]
Also, how to use the -m command?

**Comment by JamieMason** [comment]
Hello, this sets the setting in pngquant – from the docs at https://pngquant.org;

```
--quality min-max

  Instructs pngquant to use the least amount of colors required to meet or exceed the max quality. If conversion results in quality below the min quality the image won't be saved (if outputting to stdout, 24-bit original will be output) and pngquant will exit with status code 99.

  min and max are numbers in range 0 (worst) to 100 (perfect), similar to JPEG.

  pngquant --quality=65-80 image.png
```

Hope this helps, thanks.

**Comment by sogen** [comment]
thanks

**Comment by gritd** [comment]
I'm trying to reduce a .png with white gradients to transparent into 8 colors but it looks like :

imageoptim --imagealpha --number-of-colors 8 'spritesheet.png'

Does not really reduce it, if I run the GUI imagealpha on the same image after and reduce it inthere to 8 colors I can clearly see the gradients roughening up, indicating it is not yet at 8 colors after running imageoptim on it. Not sure what I'm doing wrong
