### ISSUE TITLE
Command not found 

### ISSUE THREAD

**Issue by stefanuswjy** [JamieMason/ImageOptim-CLI#125]
Basically, I'm a designer with a limited understanding of coding. I've follow your instructions about manual installation and usage. But, it didn't work. The terminal says the `-bash: imageoptim: command not found`

![imageoptim 1](https://cloud.githubusercontent.com/assets/20393960/16723297/4edaf98c-4776-11e6-8a24-0771e5200675.jpg)
![imageoptim 2](https://cloud.githubusercontent.com/assets/20393960/16723884/e394cd70-4779-11e6-96f7-57da10301c07.jpg)

This would be a lifesaver for me if it works. But, I'm facing a huge knowledge barrier :(
ps: sorry for my bad english

**Comment by JamieMason** [comment]
Duplicate of #124
