### ISSUE TITLE
include mozjpeg in benchmark

### ISSUE THREAD

**Issue by jippi** [JamieMason/ImageOptim-CLI#126]
Hi

Would it be possible to include `mozjpeg` ( https://github.com/mozilla/mozjpeg ) to the comparison ? :)

**Comment by jippi** [comment]
slightly relevant to #77

**Comment by JamieMason** [comment]
Hey @jippi,
a newer version of the comparison has moved to;

+ http://jamiemason.github.io/image-optimisation-tools-comparison
+ https://github.com/JamieMason/image-optimisation-tools-comparison

I've been busy with some other projects but plan to return to it, if you could create a pull request there it would be a great help to us all.

I will close this one here in the meantime, thanks.
