### ISSUE TITLE
ImageOptim-CLI not working. "**imageoptim-cli/png: No such file or directory"

### ISSUE THREAD

**Issue by shannonchou** [JamieMason/ImageOptim-CLI#127]
shannon$ imageoptim -a -c -d .
sort: string comparison failed: Illegal byte sequence
sort: Set LC_ALL='C' to work around the problem.
sort: The strings compared were `./IMAGES.XCASSETS/ZANH_NIGHT.IMAGESET/1ɦ\226ɡ\234ICON_09@2X.PNG' and`./IMAGES.XCASSETS/ZANH_NIGHT.IMAGESET/1ɦ\226ɡ\234ICON_09@3X.PNG'.
Running ImageAlpha...
find: /var/folders/y5/kxqqgdz53hj40k6019j89vt00000gp/T/imageoptim-cli/png: No such file or directory
Running ImageOptim...
XPC message error: Connection invalid
Runtime error (func=(main), adr=9): Divide by zero
(standard_in) 2: parse error
TOTAL was: 0kb now: 0kb saving: 0kb (%)

shannon$ echo $TMPDIR
/var/folders/y5/kxqqgdz53hj40k6019j89vt00000gp/T/

shannon$ imageoptim -v
1.14.8

ImageOptim  1.6.1
ImageAlpha   1.5.0

**Comment by JamieMason** [comment]
I'm not sure but here are a few questions/ideas;

+ Are `IMAGES.XCASSETS` or `ZANH_NIGHT.IMAGESET` regular file system directories? Or another kind of bundle format? If the latter it might be that ImageOptim.app is unable to access them.
+ You have a mix of back slashes and forward slashes in `./IMAGES.XCASSETS/ZANH_NIGHT.IMAGESET/1ɦ\226ɡ`, shouldn't they be all `/`?
+ The character `ɦ` _may_ not be handled properly.

To isolate the cause, could you try taking a screenshot then running ImageOptim-CLI over your Desktop directory? And see if everything runs correctly from there.
