### ISSUE TITLE
JpegMini doen't work

### ISSUE THREAD

**Issue by adrianmihalko** [JamieMason/ImageOptim-CLI#128]
Hi,

I am trying to run ImageOptim-CLI under Sierra, but I got error:

`/usr/local/bin/imageOptimAppleScriptLib:3009:3085: execution error: System Events got an error: Can’t get text field 1 of sheet 1 of sheet 1 of window 1 of process "JPEGmini". Invalid index. (-1719)`

Terminal access was enabled in Security&Privacy

**Comment by Anthony-Reboul** [comment]
Same problem here. I think it comes from the new macOS (Sierra). Last opened ticket on this problem : https://github.com/JamieMason/ImageOptim-CLI/issues/106

**Comment by moerphie** [comment]
+1 
same issue here.

**Comment by JamieMason** [comment]
Thanks, I will close this as a duplicate of #129 so please subscribe to that issue.
