### ISSUE TITLE
Wrong version number

### ISSUE THREAD

**Issue by paleite** [JamieMason/ImageOptim-CLI#135]
Installed, 1.14.9, but running
`imageOptim --version`
yields
1.14.8

I think this may be the culprit: https://github.com/JamieMason/ImageOptim-CLI/blob/master/bin/imageOptimBashLib

**Comment by JamieMason** [comment]
Agh, thanks @paleite I'll get this sorted – it's been a while since I did a release and I forgot this step.

**Comment by JamieMason** [comment]
The version number is correct again in [1.15.1](https://github.com/JamieMason/ImageOptim-CLI/blob/master/CHANGELOG.md#1151-2017-06-29). Thanks for reporting this.
