### ISSUE TITLE
Optimise an array of images from Node.js

### ISSUE THREAD

**Issue by jvolker** [JamieMason/ImageOptim-CLI#136]
I would like to do optimisations of multiple images in an array from Node.Js. ImageOptim-CLI currently only allows to scan whole directories. So is there a way to pass the array of file paths to ImageOptim-CLI?

Thanks!

**Comment by JamieMason** [comment]
Please see the heading "Optimise a filtered set of images" in the README.md. This project is a bash script so you would need to invoke it via child_process in the usual way. Thanks @jvolker 👍

**Comment by jvolker** [comment]
Thanks for your answer!

So there is no direct way of passing an array or list of files to the script? It always has to be run through `find`?

Thanks in advance.

**Comment by JamieMason** [comment]
you got it!
