### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by raduc** [JamieMason/ImageOptim-CLI#137]
I am getting this error:
.../bin/imageOptimBashLib: line 284: /tmpimageoptim-cli/index.txt: No such file or directory

This is caused by the concatenation:
TEMP_PATH="${TMPDIR}imageoptim-cli"

At least on my systems TMPDIR is /tmp so it causes a concatenation issue.
I understand the slash was removed here: https://github.com/JamieMason/ImageOptim-CLI/issues/87
But then it should use a proper path concatenation way to account for both existing or missing slash at the end.
Though multiple slashes should not cause an issue:
https://stackoverflow.com/a/24026057

**Comment by JamieMason** [comment]
Thanks for this @raduc and sorry for the delay, I'll look into this.
