### ISSUE TITLE
ImageOptim always quits 

### ISSUE THREAD

**Issue by jamesstout** [JamieMason/ImageOptim-CLI#140]
There is a [flag](https://github.com/ImageOptim/ImageOptim/blob/master/imageoptim/main.m#L24) in the ImageOptim code that determines if the app should quit when done:

```objc
int main(int argc, char *argv[]) {
    quitWhenDone = hideLogs = isLaunchedWithCliArguments(argc, argv);
```

This is always set to true due to the call to ImageOptim in [ImageOptimBashLib](https://github.com/JamieMason/ImageOptim-CLI/blob/master/src/imageOptimBashLib#L454):

```bash
"${location}Contents/MacOS/ImageOptim" 2> /dev/null "${TEMP_PATH}"
```
The `"${TEMP_PATH}"` is the arg that sets `quitWhenDone` to 1, so the app quits.

Not sure of the fix, it's not the end of the world, but I quite like to inspect what ImageOptim has done.

Maybe another arg to ImageOptim, but that would need help from @pornel.

**Comment by pornel** [comment]
What would be your preferred behavior?

**Comment by JamieMason** [comment]
\*poke\* @jamesstout

**Comment by jamesstout** [comment]
Maybe a flag that gets checked first that says "don't quit when done"?

````objc
static int isLaunchedWithCliArguments(int argc, char *argv[]) {
    // Unfortunately NSApplicationLaunchIsDefaultLaunchKey doesn't cover bare CLI launch
    if (argc < 2) return 0;
    for (int i=0; i < argc; i++) {
        if ([[NSString stringWithFormat:@"%s", argv[i]] isEqual:@"--dont-quit-when-done"]) {
            return 0;
        }
        if ('-' == argv[i][0]) { // Normal OS X launch sets -psn
            return 0;
        }
    }
    return 1;
}
````
Or if you want to stick with C strings:
````objc
#include <string.h>

static int isLaunchedWithCliArguments(int argc, char *argv[]) {
    // Unfortunately NSApplicationLaunchIsDefaultLaunchKey doesn't cover bare CLI launch
    if (argc < 2) return 0;
    for (int i=0; i < argc; i++) {
        if(strcmp(argv[i], "--dont-quit-when-done") == 0){
            return 0;
        }
        if ('-' == argv[i][0]) { // Normal OS X launch sets -psn
            return 0;
        }
    }
    return 1;
}
````

**Comment by jamesstout** [comment]
Option 1: https://github.com/ImageOptim/ImageOptim/compare/master...jamesstout:dont-quit-when-done
Option 2: https://github.com/ImageOptim/ImageOptim/compare/master...jamesstout:dont-quit-when-done-cstring

**Comment by pornel** [comment]
I'm not interested in implementation part. "Not quitting" can be done even easier by deleting all the qutting logic I've deliberately put in there.
 
I'm more interested in understanding *why* quitting is a problem, and how do you want ImageOptim to behave.

Note that when it's launched directly from CLI, it crates multiple copies. If you run it 20 times, you'll have 20 ImageOptim windows sitting idle. Surely, that's not a desireable behavior?

There's another alternative that already exists and works, which is to use the `open -a ImageOptim` command, which will find an existing running instance and add files to it. That doesn't quit automatically.

**Comment by jamesstout** [comment]
Yeah, thinking about it, if imageOptim doesn’t exit then Jamie’s imageOptimBashLib doesn’t know imageOptim has finished.

Really, I just noticed that the -q option in imageOptim-CLI doesn’t work, or rather, if you don’t provide that arg, then imageOptim still quits, and I wondered why. Not really thinking about how it should behave.

Quitting isn’t a problem, in fact as it stands, it has to quit.

Forget all this, I’ll play around with open -a

Thanks
James

**Comment by jamesstout** [comment]
Here's a version that doesn't quit if you don't pass the -q arg. Not sure if you want to change things at this point, but I just **_had_** to figure it out :)

https://github.com/JamieMason/ImageOptim-CLI/compare/master...jamesstout:dont-quit-when-done
