### ISSUE TITLE
JPEGMini refuses to accept shortcuts 

### ISSUE THREAD

**Issue by eighteentee** [JamieMason/ImageOptim-CLI#143]
Running ImageOptim with the -j or --jpeg-mini flags causes JPEGMini to start but not do anything. You can hear 'dings' and the simulated keypresses are sent to the app but nothing happens. This is with both Terminal.app and JPEGMini.app added to the security section of the Control Panel. No such problem with ImageOptim.app though. Running OSX 10.11.6

**Comment by JamieMason** [comment]
When I have time I plan to rewrite this project and handle this but if there are any message windows shown by JPEGmini they will need manually clicking off at the moment, they should only need dismissing once and then will not be shown again.

Is this the case with you?

**Comment by eighteentee** [comment]
Hi Jamie,

Thanks for the quick reply!

No, basically JPEGMini fires up but nothing happens, although you can hear the ‘ding’ sounds of failed keypresses. I notice that bringing up the File menu in JPEGMini shows the ‘open’ option greyed out...

Kind regards,

Phill Horrocks
Marketing Director
H&I Ltd
Auctioneers | Valuers | Asset Disposal



Office: 01200 44 33 66
Mobile: 07515 384 160
Skype: phill.horrocks@outlook.com
Email: phill@handiauctions.com
Web: bit.do/ukauctions <http://bit.do/ukauctions>

H&I Ltd is a private limited company registered in England and Wales, No. 08823120, VAT No. GB177052993

**Comment by JamieMason** [comment]
I've not seen this before, what is the version number of JPEGmini please? Maybe this is something new.

**Comment by eighteentee** [comment]
It's v 1.9.0 Build 96

**Comment by eighteentee** [comment]
The word is that there is no cmd+o to open an 'open' dialogue in the newer versions...

**Comment by JamieMason** [comment]
Disabling cmd+o will make it difficult (probably impossible) to automate their UI 👎

**Comment by stefancrain** [comment]
I have version 1.9.9 build 121 and I see the **cmd+O** menu option, maybe an upgrade could help?
![screen shot 2017-05-02 at 10 44 31 am 2](https://cloud.githubusercontent.com/assets/330720/25623202/8e7728fe-2f24-11e7-9b66-5ebd539eb74d.png)

**Comment by JamieMason** [comment]
have you had time to try 👆🏻 @eighteentee?

**Comment by eighteentee** [comment]
Yes, upgraded to the Pro version and it works A-OK. Just one question; is JPEGMini Pro meant to close when it's finished or just remain open? It remains open for me - not sure if this is right?

**Comment by JamieMason** [comment]
I think you'll just need;

```
-q, --quit            quit all apps when complete
```

**Comment by eighteentee** [comment]
Yep! That did it! Perfecto
