### ISSUE TITLE
How to run on one file 

### ISSUE THREAD

**Issue by awebdeveloper** [JamieMason/ImageOptim-CLI#145]
running doesn't work 

`imageoptim  --quit --no-color --image-alpha ica-slidebox-img-2-2-4.png`

but this works 

`find 'ica-slidebox-img-2-2-4.png'  |  imageoptim  --quit --no-color --image-alpha --min-quality 60
`

**Comment by JamieMason** [comment]
Thanks for sharing @awebdeveloper 👍

**Comment by awebdeveloper** [comment]
my question was why doesn't this support single file

**Comment by JamieMason** [comment]
The 2nd snippet matches the documentation example https://github.com/JamieMason/ImageOptim-CLI#optimise-a-filtered-set-of-images but the first does not match any of the examples. Either files are piped into `imageoptim` or a directory is passed in via `-d path/to/images` or `--directory path/to/images`.

**Comment by awebdeveloper** [comment]
don't you think adding a option to support single image is needed

**Comment by JamieMason** [comment]
Thanks @awebdeveloper, but it's already possible to optimise single files using `imageoptim`. The way this can be achieved is via piping. The number of options is already very large and I don't want to add another for existing functionality.

Related: #73, #80.

**Comment by okovpashko** [comment]
@JamieMason what can you suggest if I want to use imageoptmi-cli together with lint-staged? It simply provides a list of matched files as the arguments for the desired command but imageoptmi-cli doesn't recognize them.

**Comment by JamieMason** [comment]
hey @okovpashko, I've not used lint-staged but I would check with them if its output can be piped into other shell commands in the same way as eg. `find`. If it can then it should be compatible with other bash scripts such as imageoptim-cli 🤞

**Comment by okovpashko** [comment]
@JamieMason thank you. Maybe do you know how to grab the arguments and pass them as stdin to another command in one line using Bash?

**Comment by JamieMason** [comment]
I'm sorry @okovpashko I don't know that.
