### ISSUE TITLE
supprot for changing imageOptim config 

### ISSUE THREAD

**Issue by nick1Jian** [JamieMason/ImageOptim-CLI#146]
For now it still need to change ImageOptim config manually. 
Can you support apply config with command? or some file input?
It will be handy if need to apply different config on sets of images.

**Comment by JamieMason** [comment]
Can you add some examples of what this would look like when using it? I don't know quite what you mean. 

Thanks

**Comment by nick1Jian** [comment]
For example, you have two set of image, one set have to optimized to quality set to lossy 90% and another to be lossy 50%. Different set of image will be use on different site.

Currently, when you are to set different quality, you have to open ImageOptim and change the config from setting panel. If we can have change quality setting in command line, we can have some script that optimize two set of image without changing the config with UI.

could be like: imageoptim -a -ImageOptimQuality 70 -d  ./path

Thanks

**Comment by JamieMason** [comment]
Oh I see, you're asking for options to be added to ImageOptim-CLI to edit the following from ImageOptim.app.

![screen shot 2017-06-21 at 09 03 30](https://user-images.githubusercontent.com/320492/27373526-8d7b0606-5660-11e7-9d7a-24d2e68f6e45.png)

I don't think those are exposed by the [ImageOptim binary](https://imageoptim.com/command-line.html), but I will revisit if they get added in the future. 

Thanks a lot for this idea.

**Comment by nick1Jian** [comment]
I don't think it's expose neither and I did not find a easy way to change that. Maybe we can replace the config file somewhere. Thank you for reading my request. ;)
