### ISSUE TITLE
Dismiss JPEGmini Welcome Panel

### ISSUE THREAD

**Issue by JamieMason** [JamieMason/ImageOptim-CLI#150]
This can be achieved with a new `if` statement at the start of the [`tell process JPEGMINI_APP_NAME`][code-scope].

There's an App called [UI Browser][ui-browser] which lets you click on bits of the OSX UI and inspect them, a little bit like the Elements panel of Chrome DevTools. Using this will let you detect whether the Welcome panel is visble and, if it is, dismiss it by clicking on something.

The paths look like this `text field 1 of sheet 1 of sheet 1 of window 1` and are references we can use in applescript to get hold of pieces of UI.

This issue is to locate and dismiss the Welcome panel.

![welcome](https://user-images.githubusercontent.com/320492/30028429-f5cbd1de-917c-11e7-8e46-d67209a87393.png)

[ui-browser]: http://pfiddlesoft.com/uibrowser/
[code-scope]: https://github.com/JamieMason/ImageOptim-CLI/blob/master/bin/imageOptimAppleScriptLib#L113

**Comment by karlhorky** [comment]
This seems to also be similar to the JPEGmini Lite welcome screen, which also needs to be manually dismissed:

<img width="446" alt="Screen Shot 2019-04-23 at 18 10 08" src="https://user-images.githubusercontent.com/1935696/56597638-285aac00-65f3-11e9-8a56-7161eca89505.png">

Or should I submit this as a separate issue?

**Comment by karlhorky** [comment]
I'm assuming both of these problems are known issues with version `2.0.4`?

The current workaround that I am using (didn't find this documented anywhere in the readme) is to manually open JPEGmini Lite before using the CLI and manually click on the "Use JPEGmini Lite" button.

Would it be a good idea to document this somewhere?
