### ISSUE TITLE
JPEGmini gets don't get the proper value at "Go to Folder:" part on macOS 10.13

### ISSUE THREAD

**Issue by MoOx** [JamieMason/ImageOptim-CLI#152]
Looks similar to #129 with a variation.

The value in "Go to Folder" modal is not update with the --directory so it keeps the previous Finder "go to folder" field (in my case a random folder on my OS that have no images) so JPEGmini is actually not doing any work.
ImageOptim itself is working (and optimising some images).

I am using macOS 10.13 GM version FYI but got this issue since I use macOS 10.13 beta. I think it's time to raise the issue as macOS 10.13 is pretty much stable :D

**Comment by JamieMason** [comment]
Thanks a lot @MoOx

**Comment by stefancrain** [comment]
10.13 is released, I'm downloading and should be online soon - @JamieMason I can tackle this.

**Comment by paleite** [comment]
Thanks @stefancrain ! Looking forward to the new version

**Comment by paleite** [comment]
@stefancrain Anything I could do to help with this? Thanks in advance!

**Comment by stefancrain** [comment]
@paleite I just got the OS installed yesterday, something causing the download to suspend and not resume when my PC went to sleep made it problematic... But I can test this now! 

Basically my steps are going to be review the code in the section as pointed out by @JamieMason last time [this message](https://github.com/JamieMason/ImageOptim-CLI/issues/129#issuecomment-273220318) and make sure we have logic to cover that. If you wanted to take a stab at it that would be a great place to start!

**Comment by JamieMason** [comment]
Thanks a lot you two, I'm away on holiday from tomorrow for a week so you won't hear from me in the meantime.

**Comment by paleite** [comment]
Sorry I hadn't had the time to do this earlier, but the fix is here. I used the tool @JamieMason referenced before: http://pfiddlesoft.com/uibrowser/index-downloads.html

Thanks for a great tool (imageOptim-cli), guys!

**Comment by jtylermurphy** [comment]
Running imageoptim-cli v1.15.3 on Mac OS 10.13.1 - Jpegmini still doesn't get the directory value in the Go To Folder. it just runs on whatever the last folder Jpegmini used.

**Comment by paleite** [comment]
@jtylermurphy Are you running JPEGmini 2.1.0?

**Comment by jtylermurphy** [comment]
2.1.0 (build 136)

I played around with it some later and edited the file imageOptimAppleScriptLib on lines 126, 127 and 129 to only have one "of sheet 1" and that fixed the issue.
