### ISSUE TITLE
Savings very little

### ISSUE THREAD

**Issue by klick** [JamieMason/ImageOptim-CLI#158]
Thank you for this tool.

I noticed that optimizations are very small, only about 7 to 10% while optimizing with the jpeg mini app the standard way the results are more drastic (around 70%) for the same image. 

Am I missing something?

**Comment by JamieMason** [comment]
Thanks @klick, I will investigate this when I next come to work on ImageOptim-CLI. At the moment it is behind other projects I'm working on but I do plan to do a rewrite and will include this in that.

**Comment by pornel** [comment]
I think it's because of lossy setting. JPEMini reduces quality. By default, ImageOptim doesn't. You can get 70-90% saving with ImageOptim by enabling lossy minification option.

**Comment by klick** [comment]
> enabling lossy minification option

Where/how do i do that? It’s not listed as an option.

**Comment by JamieMason** [comment]
From Preferences Menu: 
![screen shot 2017-12-07 at 13 53 35](https://user-images.githubusercontent.com/320492/33718636-0d0507ee-db56-11e7-8f3f-97ce94414d4f.png)

I just want to check I understand this issue properly, how I understood it was that you ran imageoptim-cli using the jpeg-mini option and noticed in the JPEGmini.app that the savings were around 70%, but in the log output from imageoptim-cli it showed a smaller saving, is that correct? 

Or are you simply saying that ImageOptim.app doesn't save as much as JPEGmini.app does and the CLI is not a factor in this?

**Comment by klick** [comment]
> Or are you simply saying that ImageOptim.app doesn't save as much as JPEGmini.app does and the CLI is not a factor in this?

This. Also using the jpegmini option opens jpegmini, triggers the open-dialogue but does not do anything before handing over to the CLI again. In any case savings are around 10%.

Maybe I am missing something or just don’t understand it. I can’t find a “ImageOptim” Preference-Pane. Is it an app after all?

**Comment by klick** [comment]
Alright. Found the app, checked the lossy option and now everything works as expected. I am stupid.

**Comment by JamieMason** [comment]
ah. great! I was just about to explain – beat me to it :)
