### ISSUE TITLE
Output quality loss information

### ISSUE THREAD

**Issue by JamieMason** [JamieMason/ImageOptim-CLI#162]
## Types of Changes

What types of changes does your issue require? Put an `x` in all the boxes that apply:

* [x] **feat**: A new feature
* [ ] **fix**: A bug fix
* [ ] **docs**: Documentation only changes
* [ ] **style**: Changes that do not affect the meaning of the code
* [ ] **refactor**: A code change that neither fixes a bug or adds a feature
* [ ] **perf**: A code change that improves performance
* [ ] **test**: Adding missing tests
* [ ] **chore**: Changes to the build process or auxiliary tools/libraries

## Description

This was a feature in `<2.0.0` of imageoptim-cli that needs reinstating.

## Suggested Solution

If ImageMagick's [compare](https://www.imagemagick.org/script/compare.php) is installed, or a NodeJS alternative exists, output quality loss information if the stats option is enabled.

**Comment by kornelski** [comment]
I would advise against using IM's compare command. It only offers naive pixel-by-pixel comparison methods, which reward distortions that are blurry, and penalize good texture-preserving codecs.

In TID2013 benchmark these methods have 30-40% correlation with human judgement, while DSSIM achieves 94% on JPEG-like distortions: https://github.com/kornelski/dssim

**Comment by JamieMason** [comment]
perfect, thanks @kornelski I will use that.
