### ISSUE TITLE
Wrong path used to launch AppleScript scripts

### ISSUE THREAD

**Issue by nicolinuxfr** [JamieMason/ImageOptim-CLI#163]
## Types of Changes

What types of changes does your issue require? Put an `x` in all the boxes that apply:

* [ ] **feat**: A new feature
* [x] **fix**: A bug fix
* [ ] **docs**: Documentation only changes
* [ ] **style**: Changes that do not affect the meaning of the code
* [ ] **refactor**: A code change that neither fixes a bug or adds a feature
* [ ] **perf**: A code change that improves performance
* [ ] **test**: Adding missing tests
* [ ] **chore**: Changes to the build process or auxiliary tools/libraries

## Description

After installing the latest version of ImageOptim using npm, I have the following error when I try to activate JPEG mini : 

```
! Command failed: osascript /Users/nicolas/osascript/is-installed.applescript com.icvt.JPEGmini-Pro
osascript: /Users/nicolas/osascript/is-installed.applescript: No such file or directory

! Please raise an issue at https://github.com/JamieMason/ImageOptim-CLI/issues

    Error: Command failed: osascript /Users/nicolas/osascript/is-installed.applescript com.icvt.JPEGmini-Pro
    osascript: /Users/nicolas/osascript/is-installed.applescript: No such file or directory


        at makeError (/usr/local/lib/node_modules/imageoptim-cli/dist/imageoptim:10024:9)
        at Promise.all.then.arr (/usr/local/lib/node_modules/imageoptim-cli/dist/imageoptim:10129:16)
        at process._tickCallback (internal/process/next_tick.js:178:7)
```

I checked, and indeed, I have no `osascripts` folder inside my home folder. 

### Setup

macOS High Sierra 10.13.4  
npm 5.10.0  
node 10.1.0  
JPEGmini standard 2.2.1

**Comment by JamieMason** [comment]
this is the problem line https://github.com/JamieMason/ImageOptim-CLI/blob/3faa790f9088e5988eccb897a67111dd54d4f57d/src/applescript.ts#L14, I think using https://github.com/nexe/nexe to create a self contained executable is causing `__dirname` to not behave in the way I would expect. I'll get this fixed urgently.

**Comment by nicolinuxfr** [comment]
Great news if you can fix it easily. :-)

**Comment by JamieMason** [comment]
I seem to have it working locally, will release soon.

**Comment by JamieMason** [comment]
Please give 2.0.2 a try and reopen if there are still issues, thanks.

**Comment by nicolinuxfr** [comment]
Works great with 2.0.2, thanks for the quick fix ! 👍

**Comment by JamieMason** [comment]
you're welcome Nicolas, it was a big one so it needed sorting ASAP 😄
