### ISSUE TITLE
Error while compressing images

### ISSUE THREAD

**Issue by rahulcbr** [JamieMason/ImageOptim-CLI#167]
Getting Error on Mac whle runnning command 
i Running ImageOptim...
! spawn /Applications/ImageOptim.app/Contents/MacOS/ImageOptim ENOENT

! Please raise an issue at https://github.com/JamieMason/ImageOptim-CLI/issues

    Error: spawn /Applications/ImageOptim.app/Contents/MacOS/ImageOptim ENOENT
        at Process.ChildProcess._handle.onexit (internal/child_process.js:217:19)
        at onErrorNT (internal/child_process.js:394:16)
        at process._tickCallback (internal/process/next_tick.js:174:19)

**Comment by JamieMason** [comment]
I will do some work to make the error message much clearer, but it looks like you do not have https://imageoptim.com/mac installed – ImageOptim-CLI automates that mac app so you will need to have it installed. Thanks.
