### ISSUE TITLE
In macOS Mojave not working

### ISSUE THREAD

**Issue by HReinard** [JamieMason/ImageOptim-CLI#168]
## Types of Changes

What types of changes does your issue require? Put an `x` in all the boxes that apply:

- [ ] **feat**: A new feature
- [ ] **fix**: A bug fix
- [ ] **docs**: Documentation only changes
- [ ] **style**: Changes that do not affect the meaning of the code
- [x ] **refactor**: A code change that neither fixes a bug or adds a feature
- [ ] **perf**: A code change that improves performance
- [ ] **test**: Adding missing tests
- [ ] **chore**: Changes to the build process or auxiliary tools/libraries

**Comment by JamieMason** [comment]
Thanks @HReinard. I think the fix for this will be very similar to that made by @paleite in #153, where the paths to UI Elements have changed from previous versions of macOs.
