### ISSUE TITLE
spawn...

### ISSUE THREAD

**Issue by HReinard** [JamieMason/ImageOptim-CLI#171]
## Types of Changes

What types of changes does your issue require? Put an `x` in all the boxes that apply:

- [ ] **feat**: A new feature
- [x ] **fix**: A bug fix
- [ ] **docs**: Documentation only changes
- [ ] **style**: Changes that do not affect the meaning of the code
- [ ] **refactor**: A code change that neither fixes a bug or adds a feature
- [ ] **perf**: A code change that improves performance
- [ ] **test**: Adding missing tests
- [ ] **chore**: Changes to the build process or auxiliary tools/libraries

**Comment by HReinard** [comment]
macbook15:~ reinard$ imageoptim -j ~/Desktop/Fotos/*.*
i Running JPEGmini Pro...
i Running ImageOptim...
! spawn /Applications/ImageOptim.app/Contents/MacOS/ImageOptim ENOENT

! Please raise an issue at https://github.com/JamieMason/ImageOptim-CLI/issues

    Error: spawn /Applications/ImageOptim.app/Contents/MacOS/ImageOptim ENOENT
        at Process.ChildProcess._handle.onexit (internal/child_process.js:231:19)
        at onErrorNT (internal/child_process.js:406:16)
        at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by JamieMason** [comment]
It looks like https://imageoptim.com/mac is not installed.

**Comment by HReinard** [comment]
Hi,
I found the reason and it's working now. 

Best regards, Reinard Schmitz 
http://mirnix.info, vom iPad 4
