### ISSUE TITLE
dist/osascript/is-installed.applescript: No such file or directory

### ISSUE THREAD

**Issue by SugarMrPoon** [JamieMason/ImageOptim-CLI#176]
Looks like I'm getting a recurrence of [this old issue](https://github.com/JamieMason/ImageOptim-CLI/issues/163).

Installed on Mavericks via homebrew ... tried uninstalling and reinstalling, without luck.  (I'm also having no luck in markdown getting the first half of the error message to appear as code...sorry about that...)

`
! Command failed: osascript /usr/local/Cellar/imageoptim-cli/2.3.6/libexec/lib/node_modules/imageoptim-cli/dist/osascript/is-installed.applescript com.icvt.JPEGmini-Pro
osascript: /usr/local/Cellar/imageoptim-cli/2.3.6/libexec/lib/node_modules/imageoptim-cli/dist/osascript/is-installed.applescript: No such file or directory

! Please raise an issue at https://github.com/JamieMason/ImageOptim-CLI/issues

    Error: Command failed: osascript /usr/local/Cellar/imageoptim-cli/2.3.6/libexec/lib/node_modules/imageoptim-cli/dist/osascript/is-installed.applescript com.icvt.JPEGmini-Pro
    osascript: /usr/local/Cellar/imageoptim-cli/2.3.6/libexec/lib/node_modules/imageoptim-cli/dist/osascript/is-installed.applescript: No such file or directory

        at makeError (/usr/local/Cellar/imageoptim-cli/2.3.6/libexec/lib/node_modules/imageoptim-cli/dist/node_modules/execa/index.js:174:9)
        at Promise.all.then.arr (/usr/local/Cellar/imageoptim-cli/2.3.6/libexec/lib/node_modules/imageoptim-cli/dist/node_modules/execa/index.js:278:16)
        at process._tickCallback (internal/process/next_tick.js:68:7)`

**Comment by JamieMason** [comment]
Thanks @SugarMrPoon, 
I'm not sure what this could be just yet.

The tarball on npm contains those files as proven here:

```
$ wget https://registry.npmjs.org/imageoptim-cli/-/imageoptim-cli-2.3.6.tgz
$ tar -tvf imageoptim-cli-2.3.6.tgz
-rw-r--r--  0 0      0        2464 26 Oct  1985 package/package.json
-rw-r--r--  0 0      0        7720 26 Oct  1985 package/CHANGELOG.md
-rw-r--r--  0 0      0        1073 26 Oct  1985 package/LICENSE
-rw-r--r--  0 0      0       10104 26 Oct  1985 package/README.md
-rwxr-xr-x  0 0      0    41681652 26 Oct  1985 package/dist/imageoptim
-rw-r--r--  0 0      0         270 26 Oct  1985 package/osascript/is-installed.applescript
-rw-r--r--  0 0      0         164 26 Oct  1985 package/osascript/quit-app.applescript
-rw-r--r--  0 0      0        3578 26 Oct  1985 package/osascript/run-jpegmini.applescript
-rw-r--r--  0 0      0         265 26 Oct  1985 package/osascript/supports-assistive-devices.applescript
```

The packaging command produces those files in the latest master as proven here:

```
$ npm pack .
npm notice
npm notice 📦  imageoptim-cli@2.3.6
npm notice === Tarball Contents ===
npm notice 2.5kB  package.json
npm notice 7.7kB  CHANGELOG.md
npm notice 1.1kB  LICENSE
npm notice 10.1kB README.md
npm notice 41.7MB dist/imageoptim
npm notice 270B   osascript/is-installed.applescript
npm notice 164B   osascript/quit-app.applescript
npm notice 3.6kB  osascript/run-jpegmini.applescript
npm notice 265B   osascript/supports-assistive-devices.applescript
npm notice === Tarball Details ===
npm notice name:          imageoptim-cli
npm notice version:       2.3.6
npm notice filename:      imageoptim-cli-2.3.6.tgz
npm notice package size:  11.9 MB
npm notice unpacked size: 41.7 MB
npm notice shasum:        92c852fa25e951d0c222c20d742b7dbf1f263aac
npm notice integrity:     sha512-w+ysPIx3Jdx/Y[...]B0D0X6UFDnQsg==
npm notice total files:   9
npm notice
```

I will take a look at the homebrew installation and see if I can reproduce. What the the imageoptim-cli command you ran look like?

**Comment by JamieMason** [comment]
I bet the version bump of nexe is the cause https://github.com/JamieMason/ImageOptim-CLI/commit/a154af09214d97d03a7b1d657cf7ff98230b709e#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L41

**Comment by JamieMason** [comment]
Give imageoptim-cli@2.3.7 a try 🤞😬
