### ISSUE TITLE
cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by 0x0480** [JamieMason/ImageOptim-CLI#177]
[xxxxx@dev-xxxxx covers]$ imageoptim --help
bash: /usr/bin/imageoptim: cannot execute binary file: Exec format error

**Comment by jamesstout** [comment]
Need a bit more info really. 

What version of macOS are on? 
How did you install imageoptim?

See: [bug_report.md](https://github.com/JamieMason/ImageOptim-CLI/raw/master/.github/ISSUE_TEMPLATE/bug_report.md)

Can you please also execute this in your terminal:

`file /usr/bin/imageoptim`

The post the output here.

**Comment by JamieMason** [comment]
Please feel free to reopen this @0x0480 if you return to it 👍
