### ISSUE TITLE
A Github Action that automatically compresses JPEGs, PNGs and WebPs in Pull Requests.

### ISSUE THREAD

**Issue by elalemanyo** [JamieMason/ImageOptim-CLI#188]
## Description
Create a Github Action that automatically compresses JPEGs, PNGs and WebPs in Pull Requests.

## Suggested Solution
Create something similar to [calibreapp/image-actions](https://github.com/calibreapp/image-actions), this action works really good but the compression is not as good as the one from ImageOptim 😊

## Help Needed
Maybe someone with experience creating GitHub Actions wants to help, I never did one 🙈

**Comment by JamieMason** [comment]
Although this is a request for someone to start a new project with/for you and is not related to activity in this repo, I'll leave this issue open for a while incase you get any takers 👍🏻 . The GitHub Action would need to run something in OSX as ImageOptim is only available for that.

**Comment by elalemanyo** [comment]
@JamieMason I think this is too complicated and not sure if it was a good idea 😬
I think it is better to close it.
Thanks

**Comment by JamieMason** [comment]
Thanks for updating, it is possible I think but yes probably a big job.
