### ISSUE TITLE
Linked website gives 404

### ISSUE THREAD

**Issue by gingerbeardman** [JamieMason/ImageOptim-CLI#190]
## Steps To Reproduce The Error
- click the link `https://foldleft.io/image-tools/`

## Expected Behaviour
- display web page 

## Actual Behaviour
- 404 error

## Version Numbers or N/A

N/A

## Help Needed

Final slash causes a problem, because `https://foldleft.io/image-tools` works fine

**Comment by JamieMason** [comment]
Thanks @gingerbeardman I will fix this. Until then it seems the trailing slash version is broken for the time being - https://foldleft.io/image-tools works

**Comment by gingerbeardman** [comment]
Indeed, as described at the bottom of my issue.

**Comment by JamieMason** [comment]
Really well done for noticing @gingerbeardman 👏

**Comment by JamieMason** [comment]
Fixed
