### ISSUE TITLE
Parentheses in filenames are not recognized

### ISSUE THREAD

**Issue by chchen2021** [JamieMason/ImageOptim-CLI#194]
## Steps To Reproduce The Error
Name a file with parentheses, e.g. "settings (V-10 Z+4).png", and then use ImageOptim CLI to process the file

## Expected Behaviour
The file will be compressed like ImageOptim GUI. 

## Actual Behaviour
Error message: "! No images matched the patterns provided"

## Version Numbers or N/A
imageoptimc-cli 3.0.7 (brew installed)
ImageOptim 1.8.9 (same with 1.8.8) 

- macOS:
- /Applications/ImageOptim.app: 1.8.9
- /Applications/ImageAlpha.app: none
- /Applications/JPEGmini.app: none

## Help Needed
Update ImageOptim-CLI to recognize filenames with parentheses.

**Comment by JamieMason** [comment]
No problem @chchen2021
