### ISSUE TITLE
Animated PNG Compression

### ISSUE THREAD

**Issue by derpycoder** [JamieMason/ImageOptim-CLI#195]
## Description

This tool is a life saver, I love it. I am using it to compress all the files in the project.

However, when I try to compress APNG file, the compressor compresses only the first frame.

I'm trying to compress the fluent emoji icons!

[Official Repo](https://github.com/microsoft/fluentui-emoji)
[Animated PNGs Repo](https://github.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis)

## Suggested Solution

Perhaps an extra command line argument saying `--strip-animation` or similar can be introduced for removal of animation.

Because by default if a png is animated, people would prefer animated png. (Reddit awards are also animated png and adoption is high.)

## Help Needed

Currently I'm using [TinyPng](https://tinypng.com), to manually compress animated png.

**Comment by JamieMason** [comment]
Thanks @derpycoder, this would be something for the [ImageOptim.app](https://imageoptim.com/mac) or [ImageAlpha](https://pngmini.com/) apps, this CLI is just a convenience to run those apps, which do the optimisation.
