### ISSUE TITLE
Youtube video in readme summary set to private

### ISSUE THREAD

**Issue by jbcoventry** [JamieMason/ImageOptim-CLI#198]
## Steps To Reproduce The Error

Click link in readme summary leading to https://www.youtube.com/watch?v=HGBounRIzSs

## Expected Behaviour

Plays a video in YouTube

## Actual Behaviour

Shows a page in YouTube that says

> Video unavailable
> This video is private

## Version Numbers or N/A

- macOS:
- /Applications/ImageOptim.app:
- /Applications/ImageAlpha.app:
- /Applications/JPEGmini.app:

## Help Needed

None. Not an issue for me but I thought that if you'd gone to the trouble of making a video then you would like to know that people can't view it.

**Comment by JamieMason** [comment]
Thanks a lot @jbcoventry, fixed! (I wonder how long ago I broke that 😆)
