### ISSUE TITLE
CLI is not installing through brew

### ISSUE THREAD

**Issue by grzegorzkrukowski** [JamieMason/ImageOptim-CLI#204]
## Steps To Reproduce The Error
Running on macOS M1 arm64 run:
- brew update
- brew install imageoptim-cli

## Expected Behaviour
Installing the CLI

## Actual Behaviour
Error:
`imageoptim-cli: The x86_64 architecture is required for this software.`

## Version Numbers or N/A
- macOS: 14.1
- /Applications/ImageOptim.app: 1.9.3

**Comment by JamieMason** [comment]
Hey @grzegorzkrukowski, please see https://github.com/JamieMason/ImageOptim-CLI/issues/191#issuecomment-1672476810. Way in the future I'd like to rewrite this to not produce an executable in the way it does but for now this is the situation re: homebrew unfortunately.
