### ISSUE TITLE
ImageAlpha doesn't seem to do anything when running CLI 

### ISSUE THREAD

**Issue by stevenalanstark** [JamieMason/ImageOptim-CLI#68]
Hello,

I love this project, great work! especially the git hook, I plan to use this a lot.

I have installed the CLI and ImageOptim and ImageAlpha, but I don't see ImageAlpha doing much of anything. Out-of-the-box my png's only reduce about 10%, which shows that only ImageOptim is working.

To troubleshoot, I opened the settings in ImageOptim and turned everything PNG off, just to see what ImageAlpha is actually doing... and, unless I am mistaken, it's not doing anything.

$ imageOptim --quit --image-alpha --directory images/
Running ImageAlpha...
Running ImageOptim...
images//paytables_spritesheet_25.png was: 256.400kb now: 256.400kb saving: 0kb (0%)
images//paytables_spritesheet_50.png was: 744.069kb now: 744.069kb saving: 0kb (0%)

Those are the original file sizes for both images.

Am I doing something wrong, or is this a bug?

OSX 10.8.5
ImageAlpha 1.3.5
ImageOptim 1.4.5

When running ImageAlpha manually on one of my png images, I get an 80% savings with default settings.

NOTE: I do not have NPM installed and I am not using the growl version. But if using either of these will fix this, that's no problem.

**Comment by ahennie** [comment]
@sonicdivx  and @stevenalanstark was this issue ever solved? can't get it to run.

**Comment by JamieMason** [comment]
So far I've not been able to reproduce this: when running over a large set of images and looking at the Activity Monitor I've been able to see `pngquant` processes coming and going.

That said, there have been a lot of requests about this so I will reopen this issue and see what more can be done.

**Comment by JamieMason** [comment]
Note: there is also some useful info in duplicate issue #95.

**Comment by 75th** [comment]
I had this issue when running the `-s` flag, because it seemed like a good idea. But with that flag, "Running ImageAlpha" was *immediately* followed by "Running ImageOptim", when it could not have possibly determined that about the 60 large PNG files I was running the script on. Removing the `-s` flag made it seemingly work normally.

**Comment by jamesstout** [comment]
Just tried this with v1.14.9, with the -s param...

I used a little function to check for CPU utilisation by `pngquant`:

````bash
function cpuuup (){
  ts=$(gdate +%s%N)
  declare pids=($(ps aux | grep pngquant | grep -v grep | awk '{print $3}'))
  pidCount=${#pids[@]}

  while [ "$pidCount" -gt 0 ]
  do
    let timeSpent=0
    for index in ${!pids[*]}
    do
      tmp=${pids[$index]}
      tmp=${tmp/\.*}
      let timeSpent+=$tmp 
    done
    
    echo "CPU Utilisation: $timeSpent%"
    sleep 3
    pids=($(ps aux | grep pngquant | grep -v grep | awk '{print $3}'))
    pidCount=${#pids[@]}
  done

   tt=$((($(gdate +%s%N) - $ts)/1000000))
   echo "Time taken: $tt ms"
}
````
Then started imageoptim in one window, then the function in another:

`./bin/imageoptim  -a -s  -d /Users/james/Desktop/png
`

It hasn't finished running yet (108 large pngs)

`pngquant` ran, and finished, here's that window:

````bash
james@Jamess-iMac: ~
$ cpuuup
CPU Utilisation: 771%
CPU Utilisation: 684%
CPU Utilisation: 687%
CPU Utilisation: 645%
CPU Utilisation: 662%
CPU Utilisation: 697%
CPU Utilisation: 700%
CPU Utilisation: 706%
CPU Utilisation: 718%
CPU Utilisation: 722%
CPU Utilisation: 681%
CPU Utilisation: 702%
CPU Utilisation: 618%
CPU Utilisation: 611%
CPU Utilisation: 692%
CPU Utilisation: 754%
CPU Utilisation: 756%
CPU Utilisation: 742%
CPU Utilisation: 754%
CPU Utilisation: 691%
CPU Utilisation: 694%
CPU Utilisation: 683%
CPU Utilisation: 572%
CPU Utilisation: 494%
CPU Utilisation: 400%
CPU Utilisation: 400%
CPU Utilisation: 390%
CPU Utilisation: 298%
CPU Utilisation: 200%
CPU Utilisation: 200%
CPU Utilisation: 200%
CPU Utilisation: 100%
Time taken: 117816 ms
````
So, about 1 min 59 s for `pngquant`

Also, other comments above seem to reference the `pngquant` within the ImageAlpha bundle, but this (maybe later version than when they made the comments) uses its own `pngquant`. 

ImageOptim finished after 24 mins (fastest optimisation level). Results were:

`TOTAL was: 413741.971kb now: 114574.059kb saving: 299167.912kb (72.00%) quality: -78.297%
`

Will try it without the `-s` next...

**Comment by jamesstout** [comment]
without the `-s` worked too. Same time, 2 mins.

**Comment by JamieMason** [comment]
Can this be closed @jamesstout? Did you find pngquant _is_ being run?

**Comment by jamesstout** [comment]
Yes, it's being run. I couldn't replicate it not running.
