### ISSUE TITLE
Gulp plugin

### ISSUE THREAD

**Issue by arthurgouveia** [JamieMason/ImageOptim-CLI#71]
Hey! Thanks for this great plugin, in the first place. I use it on a daily basis.

Are you planning to implement a Gulp plugin for ImageOptim as well?

ps.: Sorry I'm opening an issue here. The only contact info I found was your GH Acc.

**Comment by reintroducing** [comment]
I know this is really old but for anyone looking here in the future there is a Gulp plugin that exists as a wrapper around this: https://github.com/allbitsnbytes/gulp-imageoptim

I needed the ability to glob images and ignore some so I explored that route and it worked great.  Prior to that this tool worked great for me as well by itself as a shell task.

**Comment by JamieMason** [comment]
Thanks a lot!
