### ISSUE TITLE
mozjpeg

### ISSUE THREAD

**Issue by glitchtracker** [JamieMason/ImageOptim-CLI#77]
Hi,
Mozilla introduced a new optimization of jpeg
https://blog.mozilla.org/research/2014/03/05/introducing-the-mozjpeg-project/

what about it vs or with jpeg mini ?

**Comment by SamHH** [comment]
Any more thoughts on this? Given that most devs won't be willing to pay for JPEGMini when there are plenty of great alternatives such as this.

**Comment by pornel** [comment]
ImageOptim.app uses mozjpeg since v1.6.0.

**Comment by SamHH** [comment]
I had no idea! Thanks for letting me know. 👍
