### ISSUE TITLE
Run Optimizilla through the performance comparison.

### ISSUE THREAD

**Issue by JamieMason** [JamieMason/ImageOptim-CLI#83]
> This online tool compresses images better than both ImageAlpha and ImageOptim http://optimizilla.com

\- http://epubsecrets.com/reduce-image-size-imageoptim.php#comment-12074

**Comment by steveleec** [comment]
I already tried pngquant and optimizilla.com. I run pngquant using grunt ant optimizilla manually (of course). However, the performance is not the same at all. by using pngquant, I got, in average, 15-20% compression. However, using optimizilla.com, I got 55-80% compression. I wish optimizilla had a npm module.

**Comment by JamieMason** [comment]
Thanks @steveleec, I think what @pornel is saying here is that Optimizilla uses pngquant but configures it to produce images of a lower quality. That should explain why the file sizes are smaller — but with a cost of them not looking as good.
