### ISSUE TITLE
ImageAlpha - No Such File or Directory

### ISSUE THREAD

**Issue by realdannys** [JamieMason/ImageOptim-CLI#87]
Hi,

I found another thread on this which I believe you fixed, but I'm trying to run it form /bin/sh and I'm getting...

Running ImageAlpha...
find: /var/folders/19/bbnc6b751llf_s9j2j09j_400000gp/T//imageoptim-cli/png: No such file or directory

Any ideas? Is it a bug or something I can fix, I was hoping to get applescript to launch it once triggered by hazel to automatically optimise screenshots...

**Comment by allbitsnbytes** [comment]
Hi Jamie,

I experienced this issue today.  I did an echo on $TMPDIR and saw that in my shell it ends with a /.  Line 26 in bin/imageOptimBashLib is the culprit.

**Comment by JamieMason** [comment]
Thanks @allbitsnbytes :+1:

**Comment by JamieMason** [comment]
This should be fixed in imageoptim-cli@1.14.8.
