### ISSUE TITLE
error message running jpegmini

### ISSUE THREAD

**Issue by jhebb** [JamieMason/ImageOptim-CLI#97]
Hi, I get the following error message when trying to run imageoptim-cli with the jpegmini option:

/usr/local/bin/imageOptimAppleScriptLib:3254:3294: execution error: System Events got an error: Can’t get button "Go" of sheet 1 of window 1 of process "JPEGmini". (-1728)

imageoptim-cli version 1.11.4
jpegmini version 1.8.6
imageoptim version 1.5.4-yosemite (but got the same error with 1.5.3)

**Comment by JamieMason** [comment]
Thanks @jhebb @jonnysperber I will close this and track the duplicate in #103.
