### ISSUE TITLE
Can't find JpegMini Pro

### ISSUE THREAD

**Issue by glitchtracker** [JamieMason/ImageOptim-CLI#98]
Hi,
I've installed the latest. Installed JpegMini Pro (latest 1.6)
but it can't find Jpeg mini pro

do shell script "/Applications/ImageOptim-CLI-master/bin/imageOptim -j -d '/FMP/FMP Scratch/Photos_majweb/'"
		--> error "[31m✘ JPEGmini is not installed (https://itunes.apple.com/us/app/jpegmini/id498944723)[0m" number 1

**Comment by JamieMason** [comment]
Sorry for the delay — @glitchtracker does this still occur in 1.11.4 please? (+ @bezelinja)

**Comment by bezelinja** [comment]
Hey,

thanks for reply. Well I did update ImageOptim to newest version although I still do get 

Error: JPEGmini is not installed (https://itunes.apple.com/us/app/jpegmini/id498944723)

There is a chance that I don't know what I'm doing tho.

**Comment by JamieMason** [comment]
What do you get back for the command `osascript -e 'id of app "JPEGmini Lite"'` please? Where "JPEGmini Lite" is either "JPEGmini" or "JPEGmini Pro", depending on what is displayed when you hover over your JPEGmini Dock icon.

**Comment by bezelinja** [comment]
com.icvt.JPEGmini-Pro

**Comment by brianroach** [comment]
I too cannot figure out how to make this work with JPEGMini Pro. Novice here so I apologize ahead of time for need a thorough walkthrough!

**Comment by JamieMason** [comment]
> But then there was problem when browsing the temporary folder. It did not launch.
> I removed the part if yosemite, if mavericks (i run maverick 10.9.5).
> 
> and put 
> keystroke return
> delay 2
> keystroke return

that's a great idea @glitchtracker, why didn't I think of that? Just hitting return - so much simpler.

**Comment by JamieMason** [comment]
I'm not ready to do a release just yet, but anyone wanting to try the latest version can run;

    npm uninstall -g imageoptim-cli
    npm install -g git+https://github.com:JamieMason/ImageOptim-CLI.git#ad692863385e69a9231c8aaea1c0f3dcf736247a

**Comment by glitchtracker** [comment]
Glad it helped you ! :-)

2015-02-12 20:02 GMT+01:00 Jamie Mason <notifications@github.com>:

**Comment by JamieMason** [comment]
Released 1.11.6
