### ISSUE TITLE
Filename with accents

### ISSUE THREAD

**Issue by qdubois** [JamieMason/ImageOptim-CLI#99]
Dear all,

ImageOptim-CLI crashed when i try to optimize a directory with filename with accents 

imageOptim  -q -c -d /Users/user/Downloads/pics/
sort: string comparison failed: Illegal byte sequence
sort: Set LC_ALL='C' to work around the problem.
sort: The strings compared were `/USERS/USER/DOWNLOADS/PICS//CAPTURE-D\302\200\231ÉCRAN-2014-11-06-À-09.40.44.PNG' and `/USERS/USER/DOWNLOADS/PICS//CERKOR0-100X50.JPG'.
Running ImageOptim...
Runtime error (func=(main), adr=9): Divide by zero

Is there anything I can do ?

Thanks

Quentin

**Comment by JamieMason** [comment]
Thanks @qdubois @pornel — closing.
